some changes
bigfoot547/bigfootbot pull request #2
Opened 2017-08-23 21:37 UTC by iraj-jelo

a `requirements.txt `and some link fixes in `bot.py` added to the project

2017-08-24 01:32 UTC, bigfoot547 requested changes

2017-08-24 01:32 UTC, bigfoot547 commented on main.conf
> +deop_owner = False
Don't forget about usermode 😛

2017-08-24 08:16 UTC, iraj-jelo commented on main.conf
> +deop_owner = False
@bigfoot547  done 👇

2017-08-26 16:45 UTC, bigfoot547 approved these changes

2017-08-26 16:45 UTC, bigfoot547 commented
Sorry, I can't merge now, I need git

2017-08-29 01:30 UTC, bigfoot547 commented
32516ad

2017-08-29 01:30 UTC, closed without merging